export interface ImageItem {
  key: string;
  label: string;
  page: "home" | "story" | "menu" | "experiences" | "outlets" | "brand";
  section: string;
  defaultUrl: string;
  description: string;
  aspectRatio: string;
  recommendedSize: string;
}

export const IMAGE_REGISTRY: ImageItem[] = [
  // Brand & Global Assets
  {
    key: "brand.logo_light",
    label: "Dark Brand Logo",
    page: "brand",
    section: "Brand Assets",
    defaultUrl: "/images/logo-r3.png",
    description: "Main Gokulam wordmark used in navbar on light backgrounds.",
    aspectRatio: "horizontal",
    recommendedSize: "400x120px PNG (transparent)",
  },
  {
    key: "brand.logo_cream",
    label: "Cream Brand Logo",
    page: "brand",
    section: "Brand Assets",
    defaultUrl: "/images/logo-cream-original.png",
    description: "Gokulam cream wordmark used in footer and dark sections.",
    aspectRatio: "horizontal",
    recommendedSize: "400x120px PNG (transparent)",
  },
  {
    key: "brand.paper_texture",
    label: "Paper Texture Pattern",
    page: "brand",
    section: "Backgrounds",
    defaultUrl: "/images/paper-texture-tile.jpg",
    description: "Subtle paper texture tiled across the entire site background.",
    aspectRatio: "pattern",
    recommendedSize: "1000x1000px seamless JPG",
  },

  // Home Page
  {
    key: "home.hero",
    label: "Hero Showcase Image",
    page: "home",
    section: "Hero Section",
    defaultUrl: "/images/DSC05117.jpg",
    description: "Primary hero image next to 'The soul of South India, on your plate'.",
    aspectRatio: "4/3",
    recommendedSize: "1200x900px WebP / JPG",
  },
  {
    key: "home.coffee_pour",
    label: "Filter Coffee Ritual Banner",
    page: "home",
    section: "Gokulam Rituals",
    defaultUrl: "/images/coffee-pour.webp",
    description: "Feature image in the 'And then, there's coffee' full-width section.",
    aspectRatio: "16/10",
    recommendedSize: "1400x875px WebP / JPG",
  },
  {
    key: "home.mysore_palace",
    label: "Mysore Palace Illustration",
    page: "home",
    section: "Landmarks & Art",
    defaultUrl: "/images/mysore-palace.png",
    description: "Decorative line-art illustration floating in the hero background.",
    aspectRatio: "landscape",
    recommendedSize: "1200x800px PNG (transparent)",
  },
  {
    key: "home.india_gate",
    label: "India Gate Illustration",
    page: "home",
    section: "Landmarks & Art",
    defaultUrl: "/images/india-gate.png",
    description: "Decorative line-art illustration at the bottom journey section.",
    aspectRatio: "landscape",
    recommendedSize: "1000x700px PNG (transparent)",
  },

  // Philosophy Badges
  {
    key: "badge.tradition",
    label: "01 Tradition Badge",
    page: "home",
    section: "Philosophy Timeline",
    defaultUrl: "/images/tradition-badge.png",
    description: "Badge icon for 'Tradition: Recipes inspired by South India'.",
    aspectRatio: "1/1",
    recommendedSize: "600x600px PNG (transparent)",
  },
  {
    key: "badge.freshness",
    label: "02 Freshness Badge",
    page: "home",
    section: "Philosophy Timeline",
    defaultUrl: "/images/freshness-badge.png",
    description: "Badge icon for 'Freshness: Batter ground daily'.",
    aspectRatio: "1/1",
    recommendedSize: "600x600px PNG (transparent)",
  },
  {
    key: "badge.craft",
    label: "03 Craft Badge",
    page: "home",
    section: "Philosophy Timeline",
    defaultUrl: "/images/craft-badge.png",
    description: "Badge icon for 'Craft: Care in every tempering'.",
    aspectRatio: "1/1",
    recommendedSize: "600x600px PNG (transparent)",
  },
  {
    key: "badge.hospitality",
    label: "04 Hospitality Badge",
    page: "home",
    section: "Philosophy Timeline",
    defaultUrl: "/images/hospitality-badge.png",
    description: "Badge icon for 'Hospitality: Warmth of South Indian hospitality'.",
    aspectRatio: "1/1",
    recommendedSize: "600x600px PNG (transparent)",
  },

  // Signature Dishes
  {
    key: "signature.masala-dosa",
    label: "Masala Dosa",
    page: "home",
    section: "Gokulam Classics",
    defaultUrl: "/images/DSC05117.jpg",
    description: "Signature card: Crisp golden dosa wrapped around spiced potato palya.",
    aspectRatio: "1/1",
    recommendedSize: "800x800px WebP / JPG",
  },
  {
    key: "signature.gokulam-thali",
    label: "Gokulam Thali",
    page: "home",
    section: "Gokulam Classics",
    defaultUrl: "/images/sig-thali.webp",
    description: "Signature card: South Indian flavours on banana leaf.",
    aspectRatio: "1/1",
    recommendedSize: "800x800px WebP / JPG",
  },
  {
    key: "signature.idli",
    label: "Idli",
    page: "home",
    section: "Gokulam Classics",
    defaultUrl: "/images/sig-idli.jpg",
    description: "Signature card: Pillow-soft idlis with hot sambar.",
    aspectRatio: "1/1",
    recommendedSize: "800x800px WebP / JPG",
  },
  {
    key: "signature.vada",
    label: "Vada",
    page: "home",
    section: "Gokulam Classics",
    defaultUrl: "/images/sig-vada.jpg",
    description: "Signature card: Crisp outside, fluffy inside.",
    aspectRatio: "1/1",
    recommendedSize: "800x800px WebP / JPG",
  },
  {
    key: "signature.filter-coffee",
    label: "Filter Coffee",
    page: "home",
    section: "Gokulam Classics",
    defaultUrl: "/images/sig-filter-coffee.webp",
    description: "Signature card: Slow brewed, frothed the davara way.",
    aspectRatio: "1/1",
    recommendedSize: "800x800px WebP / JPG",
  },
  {
    key: "signature.onion-uttapam",
    label: "Onion Uttapam",
    page: "home",
    section: "Gokulam Classics",
    defaultUrl: "/images/sig-uttapam.jpg",
    description: "Signature card: Thick and fluffy, topped with onion & chilli.",
    aspectRatio: "1/1",
    recommendedSize: "800x800px WebP / JPG",
  },

  // Menu Categories
  {
    key: "menu.breakfast",
    label: "Breakfast Category",
    page: "menu",
    section: "Menu Categories",
    defaultUrl: "/images/breakfast-spread.webp",
    description: "Cover image for Breakfast menu category (idlis, vadas, pongal).",
    aspectRatio: "1/1",
    recommendedSize: "800x800px WebP / JPG",
  },
  {
    key: "menu.dosas",
    label: "Dosas Category",
    page: "menu",
    section: "Menu Categories",
    defaultUrl: "/images/DSC05117.jpg",
    description: "Cover image for Dosas menu category.",
    aspectRatio: "1/1",
    recommendedSize: "800x800px WebP / JPG",
  },
  {
    key: "menu.idlis-vadas",
    label: "Idlis & Vadas Category",
    page: "menu",
    section: "Menu Categories",
    defaultUrl: "/images/sig-idli.jpg",
    description: "Cover image for Idlis & Vadas category.",
    aspectRatio: "1/1",
    recommendedSize: "800x800px WebP / JPG",
  },
  {
    key: "menu.thalis",
    label: "Thalis Category",
    page: "menu",
    section: "Menu Categories",
    defaultUrl: "/images/sig-thali.webp",
    description: "Cover image for Thalis and meal platters category.",
    aspectRatio: "1/1",
    recommendedSize: "800x800px WebP / JPG",
  },
  {
    key: "menu.beverages",
    label: "Beverages Category",
    page: "menu",
    section: "Menu Categories",
    defaultUrl: "/images/coffee-pour.webp",
    description: "Cover image for Filter Coffee, Buttermilk, Panakam.",
    aspectRatio: "1/1",
    recommendedSize: "800x800px WebP / JPG",
  },
  {
    key: "menu.desserts",
    label: "Desserts Category",
    page: "menu",
    section: "Menu Categories",
    defaultUrl: "/images/dessert.webp",
    description: "Cover image for Payasam, Kesari Bath, Holige.",
    aspectRatio: "1/1",
    recommendedSize: "800x800px WebP / JPG",
  },

  // Our Story Page
  {
    key: "story.slide_1",
    label: "Story Slideshow 1",
    page: "story",
    section: "Story Slideshow",
    defaultUrl: "/images/story-interior.webp",
    description: "First slide in the Our Story carousel (warm dining hall).",
    aspectRatio: "4/3",
    recommendedSize: "1200x900px WebP / JPG",
  },
  {
    key: "story.slide_2",
    label: "Story Slideshow 2",
    page: "story",
    section: "Story Slideshow",
    defaultUrl: "/images/DSC04900.jpg",
    description: "Second slide in the Our Story carousel (restaurant ambience).",
    aspectRatio: "4/3",
    recommendedSize: "1200x900px WebP / JPG",
  },
  {
    key: "story.slide_3",
    label: "Story Slideshow 3",
    page: "story",
    section: "Story Slideshow",
    defaultUrl: "/images/DSC04906.jpg",
    description: "Third slide in the Our Story carousel (dining experience).",
    aspectRatio: "4/3",
    recommendedSize: "1200x900px WebP / JPG",
  },
  {
    key: "story.rituals",
    label: "Everyday Rituals Feature",
    page: "story",
    section: "Story Content",
    defaultUrl: "/images/DSC04906.jpg",
    description: "Feature image alongside 'Made the slow way, on purpose'.",
    aspectRatio: "4/3",
    recommendedSize: "1200x900px WebP / JPG",
  },

  // Experiences Page
  {
    key: "experience.everyday-classics",
    label: "Everyday Classics",
    page: "experiences",
    section: "Experiences",
    defaultUrl: "/images/breakfast-spread.webp",
    description: "Card for Everyday Classics experience.",
    aspectRatio: "16/10",
    recommendedSize: "1000x625px WebP / JPG",
  },
  {
    key: "experience.seasonal-menus",
    label: "Seasonal Menus",
    page: "experiences",
    section: "Experiences",
    defaultUrl: "/images/sig-uttapam.jpg",
    description: "Card for Seasonal Menus (Pongal specials, summer rasam).",
    aspectRatio: "16/10",
    recommendedSize: "1000x625px WebP / JPG",
  },
  {
    key: "experience.special-menus",
    label: "Special Menus",
    page: "experiences",
    section: "Experiences",
    defaultUrl: "/images/sig-idli.jpg",
    description: "Card for Special dietary & Jain friendly selections.",
    aspectRatio: "16/10",
    recommendedSize: "1000x625px WebP / JPG",
  },
  {
    key: "experience.celebrations",
    label: "Celebrations",
    page: "experiences",
    section: "Experiences",
    defaultUrl: "/images/family-meal.webp",
    description: "Card for Family, birthdays, celebrations & group feasts.",
    aspectRatio: "16/10",
    recommendedSize: "1000x625px WebP / JPG",
  },

  // Outlets
  {
    key: "outlet.delhi-janpath",
    label: "Delhi Janpath Outlet",
    page: "outlets",
    section: "Outlets Network",
    defaultUrl: "/images/outlet-delhi.webp",
    description: "Photo of Gokulam Janpath, Connaught Place.",
    aspectRatio: "16/10",
    recommendedSize: "1200x750px WebP / JPG",
  },
  {
    key: "outlet.noida-sector-62",
    label: "Noida Sector 62 Outlet",
    page: "outlets",
    section: "Outlets Network",
    defaultUrl: "/images/DSC04900.jpg",
    description: "Photo of Gokulam Sector 62, Noida Electronic City.",
    aspectRatio: "16/10",
    recommendedSize: "1200x750px WebP / JPG",
  },
];

/** Map of key -> defaultUrl */
export const DEFAULT_IMAGE_MAP: Record<string, string> = IMAGE_REGISTRY.reduce(
  (acc, item) => {
    acc[item.key] = item.defaultUrl;
    return acc;
  },
  {} as Record<string, string>
);

export const PAGE_CATEGORIES = [
  { id: "all", label: "All Images", icon: "LayoutGrid" },
  { id: "home", label: "Home Page", icon: "Home" },
  { id: "story", label: "Our Story", icon: "BookOpen" },
  { id: "menu", label: "Menu Categories", icon: "UtensilsCrossed" },
  { id: "experiences", label: "Experiences", icon: "Sparkles" },
  { id: "outlets", label: "Outlets", icon: "MapPin" },
  { id: "brand", label: "Brand & Assets", icon: "Palette" },
] as const;
