-- ==============================================================================
-- GOKULAM CMS - SUPABASE DATABASE & STORAGE INITIALIZATION SCRIPT
-- ==============================================================================
-- Run this in your Supabase project's SQL Editor (Dashboard > SQL Editor > New Query)
-- It creates the site_images table, configures RLS, and sets up the storage bucket.
-- ==============================================================================

-- 1. Create table for site dynamic image overrides
CREATE TABLE IF NOT EXISTS public.site_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    url TEXT NOT NULL,
    alt TEXT DEFAULT '',
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.site_images ENABLE ROW LEVEL SECURITY;

-- 2. Drop any existing policies to allow re-running cleanly
DROP POLICY IF EXISTS "Public can view site images" ON public.site_images;
DROP POLICY IF EXISTS "Anyone can insert or update site images" ON public.site_images;
DROP POLICY IF EXISTS "Anyone can delete site images" ON public.site_images;

-- 3. RLS Policies: Allow public read, and allow anon/authenticated key write
CREATE POLICY "Public can view site images"
    ON public.site_images
    FOR SELECT
    USING (true);

CREATE POLICY "Anyone can insert or update site images"
    ON public.site_images
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- 4. Create public storage bucket for image uploads
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'gokulam-media',
    'gokulam-media',
    true,
    10485760, -- 10MB limit
    ARRAY['image/jpeg', 'image/jpg', 'image/png', 'image/webp', 'image/svg+xml', 'image/gif']
)
ON CONFLICT (id) DO UPDATE SET
    public = true,
    file_size_limit = 10485760;

-- 5. Storage RLS Policies (Allow public view and upload to gokulam-media)
DROP POLICY IF EXISTS "Public Access gokulam-media" ON storage.objects;
DROP POLICY IF EXISTS "Public Upload gokulam-media" ON storage.objects;
DROP POLICY IF EXISTS "Public Update gokulam-media" ON storage.objects;
DROP POLICY IF EXISTS "Public Delete gokulam-media" ON storage.objects;

CREATE POLICY "Public Access gokulam-media"
    ON storage.objects FOR SELECT
    USING (bucket_id = 'gokulam-media');

CREATE POLICY "Public Upload gokulam-media"
    ON storage.objects FOR INSERT
    WITH CHECK (bucket_id = 'gokulam-media');

CREATE POLICY "Public Update gokulam-media"
    ON storage.objects FOR UPDATE
    USING (bucket_id = 'gokulam-media');

CREATE POLICY "Public Delete gokulam-media"
    ON storage.objects FOR DELETE
    USING (bucket_id = 'gokulam-media');

-- ==============================================================================
-- DONE! Your Supabase database is now ready for the Gokulam Admin CMS.
-- ==============================================================================
