"use client";

import React, { useState, useEffect } from "react";
import {
  X,
  Database,
  CheckCircle2,
  AlertCircle,
  Copy,
  Check,
  ExternalLink,
  RefreshCw,
  Sparkles,
  Key,
  Globe,
  Trash2,
} from "lucide-react";
import {
  getSupabaseCredentials,
  saveSupabaseCredentials,
  clearSupabaseCredentials,
  testSupabaseConnection,
} from "@/lib/supabase";

interface SupabaseSettingsModalProps {
  isOpen: boolean;
  onClose: () => void;
  onCredentialsUpdated: () => void;
}

const SQL_SETUP_SNIPPET = `-- ==========================================
-- GOKULAM SUPABASE DATABASE & STORAGE SETUP
-- ==========================================
-- 1. Create table for site dynamic image overrides
CREATE TABLE IF NOT EXISTS public.site_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    url TEXT NOT NULL,
    alt TEXT DEFAULT '',
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.site_images ENABLE ROW LEVEL SECURITY;

-- Drop old policies
DROP POLICY IF EXISTS "Public can view site images" ON public.site_images;
DROP POLICY IF EXISTS "Anyone can insert or update site images" ON public.site_images;
DROP POLICY IF EXISTS "Anyone can delete site images" ON public.site_images;

-- Allow public read and full write
CREATE POLICY "Public can view site images"
    ON public.site_images FOR SELECT USING (true);

CREATE POLICY "Anyone can insert or update site images"
    ON public.site_images FOR ALL USING (true) WITH CHECK (true);

-- 2. Create public storage bucket for image uploads
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'gokulam-media',
    'gokulam-media',
    true,
    10485760, -- 10MB
    ARRAY['image/jpeg', 'image/jpg', 'image/png', 'image/webp', 'image/svg+xml', 'image/gif']
)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Storage policies
DROP POLICY IF EXISTS "Public Access gokulam-media" ON storage.objects;
DROP POLICY IF EXISTS "Public Upload gokulam-media" ON storage.objects;

CREATE POLICY "Public Access gokulam-media"
    ON storage.objects FOR SELECT USING (bucket_id = 'gokulam-media');

CREATE POLICY "Public Upload gokulam-media"
    ON storage.objects FOR ALL USING (bucket_id = 'gokulam-media') WITH CHECK (bucket_id = 'gokulam-media');
`;

export default function SupabaseSettingsModal({
  isOpen,
  onClose,
  onCredentialsUpdated,
}: SupabaseSettingsModalProps) {
  const [url, setUrl] = useState("");
  const [anonKey, setAnonKey] = useState("");
  const [isTesting, setIsTesting] = useState(false);
  const [testResult, setTestResult] = useState<{
    success: boolean;
    message: string;
  } | null>(null);
  const [copiedSql, setCopiedSql] = useState(false);
  const [saveSuccess, setSaveSuccess] = useState(false);

  useEffect(() => {
    if (isOpen) {
      const creds = getSupabaseCredentials();
      if (creds) {
        setUrl(creds.url);
        setAnonKey(creds.anonKey);
      }
      setTestResult(null);
      setSaveSuccess(false);
    }
  }, [isOpen]);

  if (!isOpen) return null;

  const handleTestConnection = async () => {
    if (!url || !anonKey) {
      setTestResult({
        success: false,
        message: "Please enter both Supabase Project URL and Anon API Key.",
      });
      return;
    }

    setIsTesting(true);
    setTestResult(null);
    try {
      const res = await testSupabaseConnection(url.trim(), anonKey.trim());
      setTestResult(res);
    } catch (err: any) {
      setTestResult({
        success: false,
        message: err.message || "Failed to connect to Supabase.",
      });
    } finally {
      setIsTesting(false);
    }
  };

  const handleSave = () => {
    if (!url || !anonKey) {
      setTestResult({
        success: false,
        message: "Please enter both Supabase URL and Anon Key.",
      });
      return;
    }

    saveSupabaseCredentials({
      url: url.trim(),
      anonKey: anonKey.trim(),
    });

    setSaveSuccess(true);
    setTimeout(() => {
      onCredentialsUpdated();
      onClose();
    }, 800);
  };

  const handleClear = () => {
    if (confirm("Are you sure you want to clear saved Supabase credentials? The site will revert to default images.")) {
      clearSupabaseCredentials();
      setUrl("");
      setAnonKey("");
      setTestResult(null);
      onCredentialsUpdated();
    }
  };

  const copySql = () => {
    navigator.clipboard.writeText(SQL_SETUP_SNIPPET);
    setCopiedSql(true);
    setTimeout(() => setCopiedSql(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="relative max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-3xl border border-sand bg-cream p-6 shadow-2xl sm:p-8">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-sand/70 pb-5">
          <div className="flex items-center gap-3">
            <div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-forest text-sand shadow">
              <Database className="h-5 w-5" />
            </div>
            <div>
              <h2 className="font-display text-2xl font-bold text-ink">
                Supabase Credentials & Setup
              </h2>
              <p className="text-xs text-ink-soft">
                Connect your Supabase project to store and persist all image changes.
              </p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="rounded-full p-2 text-ink-soft transition-colors hover:bg-sand/30 hover:text-ink"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Credentials Form */}
        <div className="mt-6 space-y-5">
          <div>
            <label className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-copper-deep">
              <Globe className="h-4 w-4" />
              <span>Project URL</span>
            </label>
            <input
              type="text"
              value={url}
              onChange={(e) => setUrl(e.target.value)}
              placeholder="https://xyzabcdefghijklm.supabase.co"
              className="mt-1.5 w-full rounded-xl border border-sand bg-parchment px-4 py-2.5 font-mono text-xs text-ink placeholder-ink-soft/40 outline-none focus:border-copper focus:ring-2 focus:ring-copper/20"
            />
            <p className="mt-1 text-[11px] text-ink-soft">
              Found in Supabase Dashboard → Settings → API → Project URL
            </p>
          </div>

          <div>
            <label className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-copper-deep">
              <Key className="h-4 w-4" />
              <span>Anon Public API Key</span>
            </label>
            <textarea
              value={anonKey}
              onChange={(e) => setAnonKey(e.target.value)}
              rows={2}
              placeholder="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
              className="mt-1.5 w-full rounded-xl border border-sand bg-parchment px-4 py-2.5 font-mono text-xs text-ink placeholder-ink-soft/40 outline-none focus:border-copper focus:ring-2 focus:ring-copper/20"
            />
            <p className="mt-1 text-[11px] text-ink-soft">
              Found in Supabase Dashboard → Settings → API → Project API keys → anon (public)
            </p>
          </div>

          {/* Test connection results */}
          {testResult && (
            <div
              className={`flex items-start gap-3 rounded-2xl p-4 text-xs ${
                testResult.success
                  ? "bg-emerald-50 text-emerald-900 border border-emerald-200"
                  : "bg-rose-50 text-rose-900 border border-rose-200"
              }`}
            >
              {testResult.success ? (
                <CheckCircle2 className="h-5 w-5 shrink-0 text-emerald-600" />
              ) : (
                <AlertCircle className="h-5 w-5 shrink-0 text-rose-600" />
              )}
              <div className="flex-1">
                <p className="font-semibold">
                  {testResult.success ? "Connection Verified!" : "Connection Failed"}
                </p>
                <p className="mt-0.5 leading-relaxed">{testResult.message}</p>
              </div>
            </div>
          )}

          {/* Buttons: Test, Save, Clear */}
          <div className="flex flex-wrap items-center justify-between gap-3 pt-2">
            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={handleTestConnection}
                disabled={isTesting || !url || !anonKey}
                className="inline-flex items-center gap-2 rounded-full border border-forest bg-cream px-5 py-2.5 text-xs font-semibold text-forest transition-colors hover:bg-forest hover:text-cream disabled:opacity-50"
              >
                <RefreshCw className={`h-3.5 w-3.5 ${isTesting ? "animate-spin" : ""}`} />
                <span>{isTesting ? "Testing..." : "Test Connection"}</span>
              </button>

              {url && (
                <button
                  type="button"
                  onClick={handleClear}
                  className="inline-flex items-center gap-1.5 rounded-full px-3 py-2 text-xs font-medium text-rose-600 transition-colors hover:bg-rose-50"
                >
                  <Trash2 className="h-3.5 w-3.5" />
                  <span>Clear</span>
                </button>
              )}
            </div>

            <button
              type="button"
              onClick={handleSave}
              disabled={!url || !anonKey}
              className="inline-flex items-center gap-2 rounded-full bg-forest px-6 py-2.5 text-xs font-semibold uppercase tracking-wider text-cream shadow transition-all hover:bg-forest-deep disabled:opacity-50"
            >
              {saveSuccess ? (
                <>
                  <Check className="h-4 w-4 text-sand" />
                  <span>Saved!</span>
                </>
              ) : (
                <>
                  <Sparkles className="h-4 w-4" />
                  <span>Save & Connect</span>
                </>
              )}
            </button>
          </div>
        </div>

        {/* Supabase SQL Setup Script Accordion / Copy */}
        <div className="mt-8 border-t border-sand/70 pt-6">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="font-display text-sm font-bold text-ink">
                1-Click Supabase SQL Setup Script
              </h3>
              <p className="text-xs text-ink-soft">
                Run this in your Supabase SQL Editor to create the table and storage bucket.
              </p>
            </div>
            <button
              type="button"
              onClick={copySql}
              className="inline-flex items-center gap-1.5 rounded-xl border border-sand bg-parchment px-3 py-1.5 text-xs font-medium text-copper-deep transition-colors hover:border-copper"
            >
              {copiedSql ? (
                <>
                  <Check className="h-3.5 w-3.5 text-emerald-600" />
                  <span className="text-emerald-700">Copied!</span>
                </>
              ) : (
                <>
                  <Copy className="h-3.5 w-3.5" />
                  <span>Copy SQL</span>
                </>
              )}
            </button>
          </div>

          <div className="relative mt-3">
            <pre className="max-h-40 overflow-x-auto rounded-xl border border-sand bg-parchment p-3 font-mono text-[11px] leading-relaxed text-ink-soft">
              {SQL_SETUP_SNIPPET}
            </pre>
          </div>

          <div className="mt-4 flex items-center justify-between text-xs text-ink-soft">
            <span>
              Also saved in your project file as <code className="font-mono text-copper-deep">supabase-setup.sql</code>
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}
