import type { MenuCategory, MenuItem } from "./types";

export interface OutletMenuInfo {
  id: string;
  slug: string;
  name: string;
  tagline: string;
  location: string;
  address: string;
  hours: string;
  phone?: string;
  pdfUrl?: string;
  categories: MenuCategory[];
}

/**
 * Gokulam Janpath - Full Authentic Extracted Menu from Brand PDF
 */
export const janpathMenuCategories: MenuCategory[] = [
  {
    id: "heritage-karnataka-best-sellers",
    slug: "heritage-karnataka-best-sellers",
    title: "Heritage Karnataka Best Sellers",
    description: "Our most celebrated signature dishes representing the finest traditions of Karnataka.",
    image: "/images/hero-dosa.webp",
    items: [
      {
        id: "janpath-benne-masala-dosa-bs",
        name: "Benne Masala Dosa",
        description: "Crispy golden fermented crepe cooked with rich aromatic white butter and stuffed with spiced potato palya.",
        price: 269,
        tags: ["signature"],
        outlet: "janpath",
        categoryId: "heritage-karnataka-best-sellers",
      },
      {
        id: "janpath-ghee-pudi-masala-dosa-bs",
        name: "Ghee Pudi Masala Dosa",
        description: "Signature crisp dosa generously smeared with fiery roasted spiced gun powder and pure desi ghee.",
        price: 260,
        tags: ["signature", "spicy"],
        outlet: "janpath",
        categoryId: "heritage-karnataka-best-sellers",
      },
      {
        id: "janpath-benne-idly-bs",
        name: "Benne Idly",
        description: "Cloud-soft steamed rice and lentil cakes crowned with melting pure butter.",
        servingDetails: "3 pieces",
        price: 255,
        tags: ["signature"],
        outlet: "janpath",
        categoryId: "heritage-karnataka-best-sellers",
      },
      {
        id: "janpath-bangalore-masala-dosa-bs",
        name: "Bangalore Masala Dosa",
        description: "Authentic Bengaluru style thick crisp dosa with potato palya and flavourful red chutney.",
        price: 260,
        tags: ["signature"],
        outlet: "janpath",
        categoryId: "heritage-karnataka-best-sellers",
      },
      {
        id: "janpath-ghee-pudi-thatte-idly-bs",
        name: "Ghee Pudi Thatte Idly",
        description: "Plate-sized traditional Karnataka thatte idly basted with fragrant podi and desi ghee.",
        servingDetails: "1 piece",
        price: 250,
        tags: ["signature", "spicy"],
        outlet: "janpath",
        categoryId: "heritage-karnataka-best-sellers",
      },
      {
        id: "janpath-chow-chow-bath-bs",
        name: "Chow-Chow Bath",
        description: "The iconic Bangalore breakfast duo — savoury Khara Bath paired with saffron Kesari Bath.",
        price: 265,
        tags: ["signature"],
        outlet: "janpath",
        categoryId: "heritage-karnataka-best-sellers",
      },
      {
        id: "janpath-iced-filter-coffee-bs",
        name: "Iced Filter Coffee",
        description: "Slow-dripped dark roast Chikmagalur coffee decoction chilled and frothed over ice.",
        price: 199,
        tags: ["signature"],
        outlet: "janpath",
        categoryId: "heritage-karnataka-best-sellers",
      },
      {
        id: "janpath-bangalore-thali-bs",
        name: "Bangalore Thali",
        description: "Wholesome authentic Karnataka feast served with fragrant rice, sambar, rasam, palya, poori and sweet.",
        price: 330,
        tags: ["signature"],
        outlet: "janpath",
        categoryId: "heritage-karnataka-best-sellers",
      },
    ],
  },
  {
    id: "idly-vada",
    slug: "idly-vada",
    title: "Idly & Vada",
    description: "Steamed morning staples and crunchy golden medu vadas served with drumstick sambar & fresh chutneys.",
    image: "/images/sig-idli.jpg",
    items: [
      {
        id: "janpath-1-idly-1-vada",
        name: "1 Idly + 1 Medu Vada",
        description: "One steamed soft idli paired with one crispy golden medu vada.",
        servingDetails: "2 pieces",
        price: 215,
        tags: [],
        outlet: "janpath",
        categoryId: "idly-vada",
      },
      {
        id: "janpath-2-idly-1-vada",
        name: "2 Idly + 1 Medu Vada Combo",
        description: "Two pillow-soft idlis paired with one crispy golden medu vada.",
        servingDetails: "3 pieces",
        price: 265,
        tags: ["combo"],
        outlet: "janpath",
        categoryId: "idly-vada",
      },
      {
        id: "janpath-medu-vada",
        name: "Medu Vada",
        description: "Crispy on the outside, fluffy inside, spiced lentil fritters served with sambar and coconut chutney.",
        servingDetails: "3 pieces",
        price: 215,
        tags: [],
        outlet: "janpath",
        categoryId: "idly-vada",
      },
      {
        id: "janpath-plain-idly",
        name: "Plain Idly",
        description: "Traditional fermented steamed rice and urad dal cakes.",
        servingDetails: "3 pieces",
        price: 220,
        tags: ["jain"],
        outlet: "janpath",
        categoryId: "idly-vada",
      },
      {
        id: "janpath-ghee-idly",
        name: "Ghee Idly",
        description: "Steamed idlis generously bathed with warm pure aromatic desi ghee.",
        servingDetails: "3 pieces",
        price: 255,
        tags: [],
        outlet: "janpath",
        categoryId: "idly-vada",
      },
      {
        id: "janpath-benne-idly",
        name: "Benne Idly",
        description: "Steamed soft idlis topped with a dollop of fresh churned white butter.",
        servingDetails: "3 pieces",
        price: 255,
        tags: [],
        outlet: "janpath",
        categoryId: "idly-vada",
      },
      {
        id: "janpath-podi-idly",
        name: "Podi Idly",
        description: "Soft idlis tossed vigorously in roasted spiced lentil gun powder and ghee.",
        servingDetails: "3 pieces",
        price: 265,
        tags: ["spicy"],
        outlet: "janpath",
        categoryId: "idly-vada",
      },
      {
        id: "janpath-rasam-idly-dip",
        name: "Rasam Idly Dip",
        description: "Pillow-soft idlis fully immersed in steaming hot tangy and peppery tomato rasam.",
        price: 265,
        tags: ["spicy"],
        outlet: "janpath",
        categoryId: "idly-vada",
      },
      {
        id: "janpath-neer-chutney-idly-dip",
        name: "Neer Chutney Idly Dip",
        description: "Idlis served dipping in fragrant seasoned watery coconut and coriander chutney.",
        price: 265,
        tags: [],
        outlet: "janpath",
        categoryId: "idly-vada",
      },
    ],
  },
  {
    id: "button-idly",
    slug: "button-idly",
    title: "Button Idly",
    description: "Bite-sized coin idlis tossed in seasoned ghee and flavorful spice powders.",
    image: "/images/sig-idli.jpg",
    items: [
      {
        id: "janpath-ghee-button-idly",
        name: "Ghee Button Idly",
        description: "Ten mini button idlis coated in pure fragrant desi ghee.",
        servingDetails: "10 pieces",
        price: 240,
        tags: [],
        outlet: "janpath",
        categoryId: "button-idly",
      },
      {
        id: "janpath-ghee-podi-button-idly",
        name: "Ghee Podi Button Idly",
        description: "Ten mini button idlis tossed in aromatic gun powder podi and ghee.",
        servingDetails: "10 pieces",
        price: 240,
        tags: ["spicy", "signature"],
        outlet: "janpath",
        categoryId: "button-idly",
      },
      {
        id: "janpath-curry-leaf-podi-button-idly",
        name: "Curry Leaf Podi Button Idly",
        description: "Ten mini button idlis coated in homemade roasted curry leaf podi and pure ghee.",
        servingDetails: "10 pieces",
        price: 240,
        tags: ["chef-special"],
        outlet: "janpath",
        categoryId: "button-idly",
      },
    ],
  },
  {
    id: "thatte-idly",
    slug: "thatte-idly",
    title: "Thatte Idly",
    description: "The pride of Bidadi & Bengaluru — large plate-sized ultra-spongy steamed idlis.",
    image: "/images/sig-idli.jpg",
    items: [
      {
        id: "janpath-plain-thatte-idly",
        name: "Plain Thatte Idly",
        description: "Extra large, cloud-soft plate idli served with coconut chutney and piping hot sambar.",
        servingDetails: "1 piece",
        price: 190,
        tags: ["jain"],
        outlet: "janpath",
        categoryId: "thatte-idly",
      },
      {
        id: "janpath-ghee-thatte-idly",
        name: "Ghee Thatte Idly",
        description: "Plate-sized thatte idli topped with a generous pour of aromatic desi ghee.",
        servingDetails: "1 piece",
        price: 210,
        tags: [],
        outlet: "janpath",
        categoryId: "thatte-idly",
      },
      {
        id: "janpath-ghee-podi-thatte-idly",
        name: "Ghee Podi Thatte Idly",
        description: "Plate idli dusted with spicy roasted gunpowder and drenched in golden ghee.",
        servingDetails: "1 piece",
        price: 250,
        tags: ["signature", "spicy"],
        outlet: "janpath",
        categoryId: "thatte-idly",
      },
      {
        id: "janpath-curry-leaf-podi-thatte-idly",
        name: "Curry Leaf Podi Thatte Idly",
        description: "Plate idli infused with aromatic roasted curry leaf spice blend and desi ghee.",
        servingDetails: "1 piece",
        price: 250,
        tags: ["chef-special"],
        outlet: "janpath",
        categoryId: "thatte-idly",
      },
    ],
  },
  {
    id: "dahi-vada-idly",
    slug: "dahi-vada-idly",
    title: "Dahi Vada & Dahi Idly",
    description: "Crispy vadas and soft idlis submerged in chilled seasoned yoghurt with mild spices.",
    image: "/images/sig-vada.jpg",
    items: [
      {
        id: "janpath-dahi-vada",
        name: "Dahi Vada",
        description: "Crisp vadas soaked in chilled, whipped sweet-and-sour spiced yoghurt with roasted cumin and boondi.",
        servingDetails: "2 pieces",
        price: 250,
        tags: [],
        outlet: "janpath",
        categoryId: "dahi-vada-idly",
      },
      {
        id: "janpath-dahi-idly",
        name: "Dahi Idly",
        description: "Steamed soft idlis soaked in chilled spiced curd, garnished with mustard crackle and coriander.",
        servingDetails: "2 pieces",
        price: 250,
        tags: [],
        outlet: "janpath",
        categoryId: "dahi-vada-idly",
      },
    ],
  },
  {
    id: "celebration-of-south-india",
    slug: "celebration-of-south-india",
    title: "Celebration of South India",
    description: "Regional delicacies celebrating the heritage recipes of Karnataka, Kerala, and Tamil Nadu.",
    image: "/images/sig-thali.webp",
    items: [
      {
        id: "janpath-karnataka-special",
        name: "Karnataka Special",
        description: "Chef's daily curated Karnataka regional festive delicacy.",
        price: 265,
        tags: ["signature"],
        outlet: "janpath",
        categoryId: "celebration-of-south-india",
      },
      {
        id: "janpath-chow-chow-bath",
        name: "Chow-Chow Bath",
        description: "The classic twin combo: savoury vegetable Khara Bath and rich Kesari Bath halwa.",
        servingDetails: "Upma + Rava Kesari",
        price: 265,
        tags: ["signature"],
        outlet: "janpath",
        categoryId: "celebration-of-south-india",
      },
      {
        id: "janpath-vegetable-upma",
        name: "Vegetable Upma",
        description: "Roasted semolina cooked with seasoned seasonal vegetables, ginger, and curry leaves.",
        price: 200,
        tags: ["jain"],
        outlet: "janpath",
        categoryId: "celebration-of-south-india",
      },
      {
        id: "janpath-kesari-bath",
        name: "Kesari Bath (Rava Kesari)",
        description: "Glistening saffron-infused semolina halwa cooked with pure ghee, cardamom, and toasted cashews.",
        price: 250,
        tags: [],
        outlet: "janpath",
        categoryId: "celebration-of-south-india",
      },
      {
        id: "janpath-jaggery-pongal",
        name: "Jaggery Pongal",
        description: "Traditional sweet rice and moong dal pudding simmered in organic jaggery and desi ghee.",
        price: 180,
        tags: ["signature"],
        outlet: "janpath",
        categoryId: "celebration-of-south-india",
      },
      {
        id: "janpath-khara-pongal",
        name: "Khara Pongal (Savoury)",
        description: "Comforting rice-and-lentil porridge tempered with crushed black pepper, cumin, ginger, and cashews.",
        servingDetails: "Rice-lentil dish",
        price: 189,
        tags: ["signature"],
        outlet: "janpath",
        categoryId: "celebration-of-south-india",
      },
      {
        id: "janpath-pongal-combo",
        name: "Pongal Combo (Sweet & Savoury)",
        description: "Platter featuring both traditional sweet Jaggery Pongal and savoury Khara Pongal.",
        price: 220,
        tags: ["combo"],
        outlet: "janpath",
        categoryId: "celebration-of-south-india",
      },
      {
        id: "janpath-bisi-bele-bath",
        name: "Bisi Bele Bath",
        description: "Karnataka's legendary hot lentil rice cooked with vegetables, tamarind, and aromatic homemade masala.",
        servingDetails: "Rice-lentil dish",
        price: 210,
        tags: ["signature", "spicy"],
        outlet: "janpath",
        categoryId: "celebration-of-south-india",
      },
      {
        id: "janpath-akki-roti",
        name: "'Akki' Roti",
        description: "Traditional Karnataka griddled rice-flour flatbread mixed with shallots, carrots, and dill leaves.",
        servingDetails: "2 pieces",
        price: 220,
        tags: ["signature"],
        outlet: "janpath",
        categoryId: "celebration-of-south-india",
      },
      {
        id: "janpath-ragi-roti",
        name: "'Ragi' Roti aka Finger Millet",
        description: "Nutritious and wholesome finger millet flatbread kneaded with chopped onions, green chilli, and herbs.",
        servingDetails: "2 pieces",
        price: 220,
        tags: ["chef-special"],
        outlet: "janpath",
        categoryId: "celebration-of-south-india",
      },
      {
        id: "janpath-poori",
        name: "Poori",
        description: "Crisp puffed golden whole wheat pooris served with traditional potato sagu.",
        price: 220,
        tags: [],
        outlet: "janpath",
        categoryId: "celebration-of-south-india",
      },
      {
        id: "janpath-appam",
        name: "Appam",
        description: "Soft bowl-shaped fermented rice hoppers with fluffy centres and lacy crisp edges, served with kurma.",
        servingDetails: "2 pieces",
        price: 240,
        tags: ["signature"],
        outlet: "janpath",
        categoryId: "celebration-of-south-india",
      },
      {
        id: "janpath-idiyappam",
        name: "Idiyappam",
        description: "Delicate steamed rice string hoppers served with mild coconut milk vegetable kurma.",
        servingDetails: "3 pieces",
        price: 240,
        tags: [],
        outlet: "janpath",
        categoryId: "celebration-of-south-india",
      },
      {
        id: "janpath-malabar-parotta",
        name: "Malabar Parotta",
        description: "Layered, flaky, hand-tossed Kerala parotta served with aromatic vegetable kurma.",
        servingDetails: "3 pieces",
        price: 260,
        tags: [],
        outlet: "janpath",
        categoryId: "celebration-of-south-india",
      },
      {
        id: "janpath-puttu-kurma",
        name: "Puttu and Kurma Curry",
        description: "Steamed layered rice flour and grated coconut cylinders served with rich vegetable kurma.",
        price: 200,
        tags: ["signature"],
        outlet: "janpath",
        categoryId: "celebration-of-south-india",
      },
    ],
  },
  {
    id: "heritage-karnataka-dosa",
    slug: "heritage-karnataka-dosa",
    title: "Heritage Karnataka Dosa",
    description: "Crisp cast-iron griddled dosas prepared using heritage fermented batter recipes.",
    image: "/images/DSC05117.jpg",
    items: [
      {
        id: "janpath-ghee-pudi-masala-dosa",
        name: "Ghee Pudi Masala Dosa",
        description: "Crispy dosa smeared with spicy roasted chutney powder, pure ghee, and potato masala.",
        price: 260,
        tags: ["signature", "spicy"],
        outlet: "janpath",
        categoryId: "heritage-karnataka-dosa",
      },
      {
        id: "janpath-mysore-masala-dosa",
        name: "Mysore Masala Dosa",
        description: "Royal Mysore specialty with spicy red garlic-chilli chutney spread inside and spiced potato filling.",
        price: 260,
        tags: ["signature", "spicy"],
        outlet: "janpath",
        categoryId: "heritage-karnataka-dosa",
      },
      {
        id: "janpath-bangalore-masala-dosa",
        name: "Bangalore Masala Dosa",
        description: "Thick golden crust dosa stuffed with traditional seasoned potato mash.",
        price: 260,
        tags: ["signature"],
        outlet: "janpath",
        categoryId: "heritage-karnataka-dosa",
      },
      {
        id: "janpath-ghee-pudi-plain-dosa",
        name: "Ghee Pudi Plain Dosa",
        description: "Crispy dosa dusted with gun powder podi and basted with pure desi ghee.",
        price: 230,
        tags: ["spicy"],
        outlet: "janpath",
        categoryId: "heritage-karnataka-dosa",
      },
      {
        id: "janpath-benne-masala-dosa",
        name: "Benne Masala Dosa",
        description: "Davanagere style butter-roasted crisp dosa with savoury potato palya.",
        price: 269,
        tags: ["signature"],
        outlet: "janpath",
        categoryId: "heritage-karnataka-dosa",
      },
      {
        id: "janpath-open-butter-masala-dosa",
        name: "Open Butter Masala Dosa 'Maharaja Special'",
        description: "Open-faced rich butter dosa topped with potato masala, roasted podi, and fresh coriander.",
        price: 269,
        tags: ["chef-special"],
        outlet: "janpath",
        categoryId: "heritage-karnataka-dosa",
      },
      {
        id: "janpath-set-masala-dosa",
        name: "Set Masala Dosa",
        description: "Trio of soft, pillowy spongy dosas served with spicy potato masala and sagu.",
        servingDetails: "3 pieces",
        price: 269,
        tags: [],
        outlet: "janpath",
        categoryId: "heritage-karnataka-dosa",
      },
      {
        id: "janpath-crispy-plain-dosa",
        name: "Crispy Plain Dosa",
        description: "Golden brown paper-thin fermented crepe served with sambar and fresh chutneys.",
        price: 189,
        tags: ["jain"],
        outlet: "janpath",
        categoryId: "heritage-karnataka-dosa",
      },
      {
        id: "janpath-classic-masala-dosa",
        name: "Classic Masala Dosa",
        description: "The timeless favourite golden dosa wrapped around spiced turmeric potato palya.",
        price: 230,
        tags: [],
        outlet: "janpath",
        categoryId: "heritage-karnataka-dosa",
      },
      {
        id: "janpath-set-dosa",
        name: "Set Dosa",
        description: "Three soft, spongy, melt-in-the-mouth dosas served with veg sagu and chutney.",
        price: 200,
        tags: [],
        outlet: "janpath",
        categoryId: "heritage-karnataka-dosa",
      },
      {
        id: "janpath-onion-plain-dosa",
        name: "Onion Plain Dosa",
        description: "Crispy griddled dosa studded with finely chopped sautéed onions.",
        servingDetails: "2 pieces",
        price: 230,
        tags: [],
        outlet: "janpath",
        categoryId: "heritage-karnataka-dosa",
      },
      {
        id: "janpath-onion-masala-dosa",
        name: "Onion Masala Dosa",
        description: "Crispy dosa layered with onions and spiced potato palya.",
        servingDetails: "2 pieces",
        price: 250,
        tags: [],
        outlet: "janpath",
        categoryId: "heritage-karnataka-dosa",
      },
      {
        id: "janpath-paper-ghee-roast",
        name: "Paper Ghee Roast",
        description: "Ultra-thin, golden crisp conical dosa generously roasted in pure aromatic desi ghee.",
        servingDetails: "3 pieces",
        price: 350,
        tags: ["chef-special", "signature"],
        outlet: "janpath",
        categoryId: "heritage-karnataka-dosa",
      },
      {
        id: "janpath-pudina-masala-dosa",
        name: "Pudina Masala Dosa",
        description: "Fresh mint-coriander spiced chutney spread inside with spiced potato filling.",
        price: 330,
        tags: [],
        outlet: "janpath",
        categoryId: "heritage-karnataka-dosa",
      },
      {
        id: "janpath-ragi-dosa",
        name: "Ragi Dosa",
        description: "Hearty, nutritious finger millet crepe made with aromatic tempering.",
        price: 210,
        tags: ["chef-special"],
        outlet: "janpath",
        categoryId: "heritage-karnataka-dosa",
      },
      {
        id: "janpath-mangalore-neer-dosa",
        name: "Mangalore Neer Dosa",
        description: "Paper-thin, light-as-air rice crepes served with coconut chutney and jaggery coconut milk.",
        price: 240,
        tags: ["signature"],
        outlet: "janpath",
        categoryId: "heritage-karnataka-dosa",
      },
    ],
  },
  {
    id: "rava-dosa-uthappam",
    slug: "rava-dosa-uthappam",
    title: "Rava Dosa & Uthappam",
    description: "Crispy lacy semolina dosas and thick, fluffy griddle uthappams with fresh toppings.",
    image: "/images/DSC05117.jpg",
    items: [
      {
        id: "janpath-mixed-uthappam",
        name: "Mixed Uthappam",
        description: "Thick, soft pancake topped with chopped onions, tomatoes, green chillies, and coriander.",
        price: 265,
        tags: [],
        outlet: "janpath",
        categoryId: "rava-dosa-uthappam",
      },
      {
        id: "janpath-tomato-uthappam",
        name: "Tomato Uthappam",
        description: "Thick griddle cake topped generously with juicy ripe tomatoes and curry leaves.",
        price: 265,
        tags: ["jain"],
        outlet: "janpath",
        categoryId: "rava-dosa-uthappam",
      },
      {
        id: "janpath-onion-uthappam",
        name: "Onion Uthappam",
        description: "Thick pillowy griddle cake crowned with caramelized chopped onions.",
        price: 265,
        tags: [],
        outlet: "janpath",
        categoryId: "rava-dosa-uthappam",
      },
      {
        id: "janpath-rava-masala-dosa",
        name: "Rava Masala Dosa",
        description: "Lacy, crackling semolina crepe with cumin and peppercorns, filled with spiced potato palya.",
        price: 315,
        tags: ["spicy"],
        outlet: "janpath",
        categoryId: "rava-dosa-uthappam",
      },
      {
        id: "janpath-rava-onion-masala-dosa",
        name: "Rava Onion Masala Dosa",
        description: "Crisp lacy semolina crepe loaded with chopped onions and savoury potato palya.",
        price: 340,
        tags: ["spicy"],
        outlet: "janpath",
        categoryId: "rava-dosa-uthappam",
      },
    ],
  },
  {
    id: "unique-must-try",
    slug: "unique-must-try",
    title: "Unique Must Try",
    description: "Iconic regional snacks and tea-time delicacies from coastal and central Karnataka.",
    image: "/images/sig-vada.jpg",
    items: [
      {
        id: "janpath-mangalore-bun",
        name: "Mangalore Bun",
        description: "Mildly sweet, fluffy, puffed banana-infused fried bread served with spicy coconut chutney.",
        servingDetails: "2 pieces",
        price: 260,
        tags: ["must-try", "signature"],
        outlet: "janpath",
        categoryId: "unique-must-try",
      },
      {
        id: "janpath-maddur-vada",
        name: "Maddur Vada",
        description: "Crispy, crunchy heritage fritters made with semolina, onions, curry leaves, and spices.",
        servingDetails: "4 pieces",
        price: 220,
        tags: ["must-try", "signature"],
        outlet: "janpath",
        categoryId: "unique-must-try",
      },
      {
        id: "janpath-mangalore-bajji",
        name: "Mangalore Bajji",
        description: "Golden, fluffy coastal fritters (Goli Baje) with crispy crust and spongy interior.",
        servingDetails: "6 pieces",
        price: 220,
        tags: ["must-try"],
        outlet: "janpath",
        categoryId: "unique-must-try",
      },
      {
        id: "janpath-masala-vada",
        name: "Masala Vada",
        description: "Crunchy Bengal gram patties blended with chopped shallots, dill, fennel, and ginger.",
        servingDetails: "4 pieces",
        price: 240,
        tags: ["must-try"],
        outlet: "janpath",
        categoryId: "unique-must-try",
      },
      {
        id: "janpath-mix-vegetable-pakkoda",
        name: "Mix Vegetable Pakkoda",
        description: "Crunchy golden fried assorted vegetable fritters tossed with roasted curry leaves and spices.",
        price: 240,
        tags: ["must-try"],
        outlet: "janpath",
        categoryId: "unique-must-try",
      },
    ],
  },
  {
    id: "fusion-idly-dosa",
    slug: "fusion-idly-dosa",
    title: "Fusion Idly & Dosa",
    description: "Modern chef-crafted gourmet twists and grand tasting platters.",
    image: "/images/DSC05117.jpg",
    items: [
      {
        id: "janpath-paneer-masala-dosa",
        name: "Paneer Masala Dosa",
        description: "Crisp golden dosa filled with spiced crumbled fresh paneer and herbs.",
        price: 350,
        tags: ["chef-special"],
        outlet: "janpath",
        categoryId: "fusion-idly-dosa",
      },
      {
        id: "janpath-cheese-plain-dosa",
        name: "Cheese Plain Dosa",
        description: "Crisp dosa blanketed with gooey melted cheese.",
        price: 320,
        tags: [],
        outlet: "janpath",
        categoryId: "fusion-idly-dosa",
      },
      {
        id: "janpath-cheese-masala-dosa",
        name: "Cheese Masala Dosa",
        description: "Spiced potato palya dosa generously loaded with melted mozzarella & cheddar cheese.",
        price: 350,
        tags: ["chef-special"],
        outlet: "janpath",
        categoryId: "fusion-idly-dosa",
      },
      {
        id: "janpath-fried-podi-idly",
        name: "Fried Podi Idly",
        description: "Crispy golden fried idli cubes tossed in roasted spicy gun powder and curry leaves.",
        price: 269,
        tags: ["spicy"],
        outlet: "janpath",
        categoryId: "fusion-idly-dosa",
      },
      {
        id: "janpath-gokulam-dosa-special",
        name: "Gokulam Dosa Special",
        description: "Grand tasting platter featuring 6 distinct mini dosas: Podi, Coconut, Pudina, Masala, Paneer and Cheese.",
        servingDetails: "6 types: Podi Dosa, Coconut Dosa, Pudina Dosa, Masala Dosa, Paneer Dosa",
        price: 450,
        tags: ["signature", "chef-special"],
        outlet: "janpath",
        categoryId: "fusion-idly-dosa",
      },
      {
        id: "janpath-gokulam-idly-special",
        name: "Gokulam Idly Special",
        description: "Grand idli platter featuring 6 specialty creations: Podi, Curry Leaf, Rasam, Ghee, and Idly Fries.",
        servingDetails: "6 types: Podi Idly, Curry Leaf Idly, Rasam Idly, Ghee Idly, Idly Fries",
        price: 320,
        tags: ["signature", "chef-special"],
        outlet: "janpath",
        categoryId: "fusion-idly-dosa",
      },
    ],
  },
  {
    id: "south-indian-traditional-rice",
    slug: "south-indian-traditional-rice",
    title: "South Indian Traditional Rice",
    description: "Hand-pounded rice preparations infused with authentic regional spices, tamarind, and tempering.",
    image: "/images/sig-thali.webp",
    items: [
      {
        id: "janpath-vangi-bath",
        name: "Vangi Bath (Brinjal Rice)",
        description: "Fragrant spiced rice cooked with tender brinjal and authentic Karnataka Vangi Bath spice blend.",
        price: 220,
        tags: ["signature"],
        outlet: "janpath",
        categoryId: "south-indian-traditional-rice",
      },
      {
        id: "janpath-lemon-rice",
        name: "Lemon Rice",
        description: "Steamed rice tempered with fresh lemon juice, mustard seeds, crunchy peanuts, and curry leaves.",
        price: 220,
        tags: ["jain"],
        outlet: "janpath",
        categoryId: "south-indian-traditional-rice",
      },
      {
        id: "janpath-temple-puliyogare",
        name: "Temple Puliyogare (Tamarind Rice)",
        description: "Traditional temple-style tangy tamarind rice simmered with sesame, jaggery, peanuts, and spices.",
        price: 220,
        tags: ["signature"],
        outlet: "janpath",
        categoryId: "south-indian-traditional-rice",
      },
      {
        id: "janpath-rasam-rice",
        name: "Rasam Rice",
        description: "Hot rice mixed with spicy, aromatic pepper-tomato rasam and a dollop of pure ghee.",
        price: 220,
        tags: ["spicy"],
        outlet: "janpath",
        categoryId: "south-indian-traditional-rice",
      },
      {
        id: "janpath-curd-rice",
        name: "Curd Rice",
        description: "Comforting creamy seasoned curd rice tempered with mustard, green chillies, ginger, and pomegranate.",
        price: 220,
        tags: ["jain"],
        outlet: "janpath",
        categoryId: "south-indian-traditional-rice",
      },
      {
        id: "janpath-sambar-rice",
        name: "Sambar Rice (Sambar)",
        description: "Hot comforting Bisi Sambar Sadam cooked with lentils, country vegetables, and pure desi ghee.",
        price: 220,
        tags: [],
        outlet: "janpath",
        categoryId: "south-indian-traditional-rice",
      },
      {
        id: "janpath-rice-combo",
        name: "Rice Combo",
        description: "Duo platter featuring your choice of two traditional South Indian rice varieties.",
        servingDetails: "Choice of 2 traditional rice",
        price: 275,
        tags: ["combo"],
        outlet: "janpath",
        categoryId: "south-indian-traditional-rice",
      },
    ],
  },
  {
    id: "thalis",
    slug: "thalis",
    title: "Thalis & Feasts",
    description: "Grand traditional South Indian feasts served with an assortment of regional curries, rice, and sweets.",
    image: "/images/sig-thali.webp",
    items: [
      {
        id: "janpath-bangalore-thali",
        name: "Bangalore Thali",
        description: "A complete Bengaluru style meal: rice, sambar, rasam, palya, kootu, poori, curd, appalam, and sweet.",
        price: 330,
        tags: ["signature"],
        outlet: "janpath",
        categoryId: "thalis",
      },
      {
        id: "janpath-special-thali",
        name: "Special Thali",
        description: "Curated grand feast with specialty seasonal curries, traditional starters, variety rice, and dessert.",
        price: 350,
        tags: ["chef-special"],
        outlet: "janpath",
        categoryId: "thalis",
      },
      {
        id: "janpath-gokulam-special-thali",
        name: "Gokulam Special Thali",
        description: "Our grandest culinary celebration: over 15 heritage delicacies served the traditional royal way.",
        price: 525,
        tags: ["signature", "chef-special"],
        outlet: "janpath",
        categoryId: "thalis",
      },
      {
        id: "janpath-mini-thali",
        name: "Mini Thali",
        description: "A lighter satisfying meal: aromatic rice, sambar, rasam, poriyal, appalam, and set curd.",
        price: 299,
        tags: [],
        outlet: "janpath",
        categoryId: "thalis",
      },
      {
        id: "janpath-mini-malabar-parotta-thali",
        name: "Mini Malabar Parotta Thali",
        description: "Two flaky layered Malabar parottas served with rich vegetable kurma, dal, and accompaniments.",
        price: 299,
        tags: [],
        outlet: "janpath",
        categoryId: "thalis",
      },
    ],
  },
  {
    id: "gokulam-value-combos",
    slug: "gokulam-value-combos",
    title: "Gokulam Value Combos",
    description: "Curated value combinations of all-time favourite dishes paired with filter coffee or tea.",
    image: "/images/coffee-pour.webp",
    items: [
      {
        id: "janpath-mini-tiffin-combo",
        name: "Mini Tiffin Combo (All Day)",
        description: "The complete mini tiffin ritual: mini dosa, medu vada, soft idli, rava kesari, and filter coffee or tea.",
        servingDetails: "Mini dosa + vada + idly + kesari rava + coffee/tea",
        price: 400,
        tags: ["signature", "combo"],
        outlet: "janpath",
        categoryId: "gokulam-value-combos",
      },
      {
        id: "janpath-podi-thatte-idly-combo",
        name: "Podi Thatte Idly + Coffee/Tea",
        description: "Spicy ghee podi thatte idli paired with authentic hot filter coffee or special tea.",
        servingDetails: "7am to 12 noon",
        price: 300,
        tags: ["combo"],
        outlet: "janpath",
        categoryId: "gokulam-value-combos",
      },
      {
        id: "janpath-benne-dosa-combo",
        name: "Benne Dosa + Coffee/Tea",
        description: "Crispy butter benne dosa served with hot filter coffee or special tea.",
        servingDetails: "7am to 12 noon",
        price: 320,
        tags: ["combo"],
        outlet: "janpath",
        categoryId: "gokulam-value-combos",
      },
      {
        id: "janpath-bangalore-masala-dosa-combo",
        name: "Bangalore Masala Dosa + Coffee/Tea",
        description: "Signature Bangalore masala dosa with authentic hot filter coffee or tea.",
        servingDetails: "7am to 12 noon",
        price: 320,
        tags: ["combo"],
        outlet: "janpath",
        categoryId: "gokulam-value-combos",
      },
      {
        id: "janpath-1-idly-1-vada-combo",
        name: "1 Idly + 1 Vada + Coffee/Tea",
        description: "One soft idli and one crispy medu vada with hot filter coffee or tea.",
        servingDetails: "7am to 12 noon",
        price: 250,
        tags: ["combo"],
        outlet: "janpath",
        categoryId: "gokulam-value-combos",
      },
      {
        id: "janpath-plain-idly-3-combo",
        name: "Plain Idly (3) + Coffee/Tea",
        description: "Three steamed soft idlis with hot filter coffee or special tea.",
        servingDetails: "7am to 12 noon",
        price: 250,
        tags: ["combo"],
        outlet: "janpath",
        categoryId: "gokulam-value-combos",
      },
      {
        id: "janpath-vada-2-combo",
        name: "Vada (2) + Coffee/Tea",
        description: "Two crispy golden medu vadas with hot filter coffee or tea.",
        servingDetails: "7am to 12 noon",
        price: 250,
        tags: ["combo"],
        outlet: "janpath",
        categoryId: "gokulam-value-combos",
      },
      {
        id: "janpath-chow-chow-bath-combo",
        name: "Chow Chow Bath + Coffee/Tea",
        description: "Savoury khara bath and sweet kesari bath paired with hot filter coffee or tea.",
        servingDetails: "7am to 12 noon",
        price: 250,
        tags: ["combo"],
        outlet: "janpath",
        categoryId: "gokulam-value-combos",
      },
      {
        id: "janpath-bisi-bele-bath-combo",
        name: "Bisi Bele Bath + Coffee/Tea",
        description: "Hot aromatic bisi bele bath served with hot filter coffee or special tea.",
        servingDetails: "7am to 12 noon",
        price: 250,
        tags: ["combo"],
        outlet: "janpath",
        categoryId: "gokulam-value-combos",
      },
    ],
  },
  {
    id: "speciality-hot-beverages",
    slug: "speciality-hot-beverages",
    title: "Speciality Hot Beverages",
    description: "Slow-brewed Chikmagalur filter coffee, spiced teas, and comforting herbal brews.",
    image: "/images/coffee-pour.webp",
    items: [
      {
        id: "janpath-special-filter-coffee",
        name: "Special Filter Coffee",
        description: "Slow-dripped dark roast coffee decoction frothed the authentic way in a traditional brass tumbler & davara.",
        price: 130,
        tags: ["signature"],
        outlet: "janpath",
        categoryId: "speciality-hot-beverages",
      },
      {
        id: "janpath-coffee-and-jaggery",
        name: "Coffee and \"Jaggery\"",
        description: "Rich dark roast filter coffee sweetened naturally with organic unrefined jaggery.",
        price: 140,
        tags: [],
        outlet: "janpath",
        categoryId: "speciality-hot-beverages",
      },
      {
        id: "janpath-black-coffee",
        name: "Black Coffee",
        description: "Pure aromatic filter coffee decoction served hot and bold.",
        price: 100,
        tags: [],
        outlet: "janpath",
        categoryId: "speciality-hot-beverages",
      },
      {
        id: "janpath-special-tea",
        name: "Special Tea",
        description: "Freshly brewed classic South Indian milk tea.",
        price: 120,
        tags: [],
        outlet: "janpath",
        categoryId: "speciality-hot-beverages",
      },
      {
        id: "janpath-ginger-tea",
        name: "Ginger Tea",
        description: "Milk tea infused with freshly crushed aromatic ginger.",
        price: 120,
        tags: [],
        outlet: "janpath",
        categoryId: "speciality-hot-beverages",
      },
      {
        id: "janpath-masala-tea",
        name: "Masala Tea",
        description: "Warm fragrant tea brewed with cardamom, clove, cinnamon, and black pepper.",
        price: 120,
        tags: [],
        outlet: "janpath",
        categoryId: "speciality-hot-beverages",
      },
      {
        id: "janpath-lemon-tea",
        name: "Lemon Tea",
        description: "Soothing clear black tea infused with fresh lemon juice and honey.",
        price: 120,
        tags: [],
        outlet: "janpath",
        categoryId: "speciality-hot-beverages",
      },
      {
        id: "janpath-black-tea",
        name: "Black Tea",
        description: "Robust, full-bodied aromatic black tea.",
        price: 100,
        tags: [],
        outlet: "janpath",
        categoryId: "speciality-hot-beverages",
      },
      {
        id: "janpath-hot-rasam",
        name: "Hot Rasam",
        description: "Steaming hot cup of medicinal pepper-tomato rasam with curry leaves and garlic.",
        price: 180,
        tags: ["spicy"],
        outlet: "janpath",
        categoryId: "speciality-hot-beverages",
      },
      {
        id: "janpath-hot-badam-milk",
        name: "Hot Badam Milk",
        description: "Rich warm milk simmered with crushed almonds, saffron, and cardamom.",
        price: 160,
        tags: [],
        outlet: "janpath",
        categoryId: "speciality-hot-beverages",
      },
      {
        id: "janpath-hot-horlicks",
        name: "Hot Horlicks",
        description: "Warm comforting malt beverage.",
        price: 150,
        tags: [],
        outlet: "janpath",
        categoryId: "speciality-hot-beverages",
      },
      {
        id: "janpath-hot-bournvita",
        name: "Hot Bournvita",
        description: "Warm comforting chocolate malt drink.",
        price: 150,
        tags: [],
        outlet: "janpath",
        categoryId: "speciality-hot-beverages",
      },
    ],
  },
  {
    id: "to-keep-you-cool",
    slug: "to-keep-you-cool",
    title: "To Keep You Cool",
    description: "Chilled coolers, spiced buttermilk, iced coffees, and freshly squeezed fruit juices.",
    image: "/images/coffee-pour.webp",
    items: [
      {
        id: "janpath-iced-filter-coffee",
        name: "Iced Filter Coffee",
        description: "Rich filter coffee decoction shaken over ice with milk and frothy foam.",
        price: 199,
        tags: ["signature"],
        outlet: "janpath",
        categoryId: "to-keep-you-cool",
      },
      {
        id: "janpath-iced-black-coffee",
        name: "Iced Black Coffee",
        description: "Bold dark roast filter coffee poured over ice cubes.",
        price: 169,
        tags: [],
        outlet: "janpath",
        categoryId: "to-keep-you-cool",
      },
      {
        id: "janpath-lemon-ice-tea",
        name: "Lemon Ice Tea",
        description: "Chilled zesty black tea infused with lemon, mint, and crushed ice.",
        price: 199,
        tags: [],
        outlet: "janpath",
        categoryId: "to-keep-you-cool",
      },
      {
        id: "janpath-cold-badam-milk",
        name: "Cold Badam Milk",
        description: "Chilled almond milk infused with saffron, cardamom, and almond slivers.",
        price: 200,
        tags: [],
        outlet: "janpath",
        categoryId: "to-keep-you-cool",
      },
      {
        id: "janpath-neer-majjige",
        name: "Neer Majjige",
        description: "Traditional churned spiced buttermilk with crushed ginger, green chilli, and fresh curry leaves.",
        price: 189,
        tags: ["jain", "signature"],
        outlet: "janpath",
        categoryId: "to-keep-you-cool",
      },
      {
        id: "janpath-mojito",
        name: "Mojito",
        description: "Crisp cooler with muddled mint leaves, fresh lime, and sparkling soda.",
        price: 200,
        tags: [],
        outlet: "janpath",
        categoryId: "to-keep-you-cool",
      },
      {
        id: "janpath-seasonal-fruit-juice",
        name: "Seasonal Fruit Juice",
        description: "Freshly squeezed seasonal fruit juice with no added preservatives.",
        price: 200,
        tags: [],
        outlet: "janpath",
        categoryId: "to-keep-you-cool",
      },
      {
        id: "janpath-lime-soda",
        name: "Lime Soda",
        description: "Sparkling soda with fresh lime juice (Sweet / Salted / Mixed).",
        price: 200,
        tags: [],
        outlet: "janpath",
        categoryId: "to-keep-you-cool",
      },
      {
        id: "janpath-soft-beverages",
        name: "Soft Beverages",
        description: "Chilled aerated soft drink cans.",
        price: 70,
        tags: [],
        outlet: "janpath",
        categoryId: "to-keep-you-cool",
      },
      {
        id: "janpath-lassi-mango-lassi",
        name: "Lassi / Mango Lassi",
        description: "Thick, creamy churned sweet yoghurt lassi or real mango pulp lassi.",
        price: 299,
        tags: [],
        outlet: "janpath",
        categoryId: "to-keep-you-cool",
      },
    ],
  },
  {
    id: "sweet-treats",
    slug: "sweet-treats",
    title: "Sweet Treats",
    description: "Desserts, ice creams, and South Indian after-meal confections.",
    image: "/images/dessert.webp",
    items: [
      {
        id: "janpath-gulkand-banana-icecream",
        name: "Gulkand with Banana and Vanilla Icecream",
        description: "Traditional sun-cooked organic damask rose preserve served with sliced fresh banana and vanilla ice cream.",
        price: 230,
        tags: ["signature"],
        outlet: "janpath",
        categoryId: "sweet-treats",
      },
      {
        id: "janpath-filter-coffee-affogato",
        name: "Filter Coffee Affogato",
        description: "Creamy vanilla ice cream topped with a hot, strong pour of freshly brewed filter coffee decoction.",
        price: 230,
        tags: ["chef-special", "signature"],
        outlet: "janpath",
        categoryId: "sweet-treats",
      },
      {
        id: "janpath-gokulam-fruit-salad-ice-cream",
        name: "Gokulam Fruit Salad with Ice Cream",
        description: "Freshly cut seasonal fruits tossed and topped with a scoop of premium ice cream.",
        price: 300,
        tags: [],
        outlet: "janpath",
        categoryId: "sweet-treats",
      },
      {
        id: "janpath-ice-cream",
        name: "Ice Cream",
        description: "Two scoops of rich ice cream in your choice of flavour.",
        servingDetails: "2 scoops; ask for options",
        price: 300,
        tags: [],
        outlet: "janpath",
        categoryId: "sweet-treats",
      },
    ],
  },
];

/**
 * Gokulam Noida (Sector 62) - Full Authentic Extracted Menu from Brand PDF
 */
export const noidaMenuCategories: MenuCategory[] = [
  {
    id: "noida-idly-vada",
    slug: "idly-vada",
    title: "Idly & Vada",
    description: "Traditional steamed idlis and crispy golden medu vadas served with drumstick sambar and fresh chutneys.",
    image: "/images/sig-idli.jpg",
    items: [
      {
        id: "noida-1-idly-1-vada",
        name: "1 Idly + 1 Medu Vada",
        description: "One steamed soft idli paired with one crispy golden medu vada.",
        servingDetails: "1 + 1",
        price: 120,
        tags: [],
        outlet: "sector-62",
        categoryId: "idly-vada",
        categoryTitle: "Idly & Vada",
      },
      {
        id: "noida-2-idly-1-vada-combo",
        name: "2 Idly + 1 Medu Vada Combo",
        description: "Two pillow-soft idlis paired with one crispy golden medu vada.",
        servingDetails: "2 + 1",
        price: 160,
        tags: ["combo"],
        outlet: "sector-62",
        categoryId: "idly-vada",
        categoryTitle: "Idly & Vada",
      },
      {
        id: "noida-medu-vada",
        name: "Medu Vada",
        description: "Crispy on the outside, fluffy inside, spiced lentil fritters served with sambar and fresh coconut chutney.",
        servingDetails: "2 pcs",
        price: 120,
        tags: [],
        outlet: "sector-62",
        categoryId: "idly-vada",
        categoryTitle: "Idly & Vada",
      },
      {
        id: "noida-plain-idly",
        name: "Plain Idly",
        description: "Traditional fermented steamed rice and urad dal cakes.",
        servingDetails: "3 pcs",
        price: 120,
        tags: ["jain"],
        outlet: "sector-62",
        categoryId: "idly-vada",
        categoryTitle: "Idly & Vada",
      },
      {
        id: "noida-ghee-idly",
        name: "Ghee Idly",
        description: "Steamed idlis generously bathed with warm pure aromatic desi ghee.",
        servingDetails: "3 pcs",
        price: 150,
        tags: [],
        outlet: "sector-62",
        categoryId: "idly-vada",
        categoryTitle: "Idly & Vada",
      },
      {
        id: "noida-bangalore-style-butter-idly",
        name: "Bangalore Style Butter Idly",
        description: "Steamed soft idlis topped with a rich dollop of fresh churned butter.",
        servingDetails: "3 pcs",
        price: 150,
        tags: ["signature"],
        outlet: "sector-62",
        categoryId: "idly-vada",
        categoryTitle: "Idly & Vada",
      },
      {
        id: "noida-ghee-podi-idly",
        name: "Ghee Podi Idly",
        description: "Soft idlis tossed vigorously in roasted spiced lentil gun powder and golden ghee.",
        servingDetails: "3 pcs",
        price: 180,
        tags: ["spicy", "signature"],
        outlet: "sector-62",
        categoryId: "idly-vada",
        categoryTitle: "Idly & Vada",
      },
    ],
  },
  {
    id: "noida-button-idly",
    slug: "button-idly",
    title: "Button Idly",
    description: "Bite-sized coin idlis tossed in seasoned ghee and aromatic spice powders.",
    image: "/images/sig-idli.jpg",
    items: [
      {
        id: "noida-ghee-button-idly",
        name: "Ghee Button Idly",
        description: "Six mini button idlis coated in pure fragrant desi ghee.",
        servingDetails: "6 pcs",
        price: 100,
        tags: [],
        outlet: "sector-62",
        categoryId: "button-idly",
        categoryTitle: "Button Idly",
      },
      {
        id: "noida-ghee-podi-button-idly",
        name: "Ghee Podi Button Idly",
        description: "Six mini button idlis tossed in aromatic gun powder podi and ghee.",
        servingDetails: "6 pcs",
        price: 120,
        tags: ["spicy", "signature"],
        outlet: "sector-62",
        categoryId: "button-idly",
        categoryTitle: "Button Idly",
      },
      {
        id: "noida-curry-leaf-podi-button-idly",
        name: "Curry Leaf Podi Button Idly",
        description: "Six mini button idlis coated in homemade roasted curry leaf podi and pure ghee.",
        servingDetails: "6 pcs",
        price: 120,
        tags: ["chef-special"],
        outlet: "sector-62",
        categoryId: "button-idly",
        categoryTitle: "Button Idly",
      },
    ],
  },
  {
    id: "noida-thatte-idly",
    slug: "thatte-idly",
    title: "Thatte Idly",
    description: "The pride of Bidadi & Bengaluru — plate-sized ultra-spongy steamed idlis.",
    image: "/images/sig-idli.jpg",
    items: [
      {
        id: "noida-plain-thatte-idly",
        name: "Plain Thatte Idly",
        description: "Large, cloud-soft plate idli served with coconut chutney and piping hot sambar.",
        servingDetails: "1 pc",
        price: 100,
        tags: ["jain"],
        outlet: "sector-62",
        categoryId: "thatte-idly",
        categoryTitle: "Thatte Idly",
      },
      {
        id: "noida-ghee-thatte-idly",
        name: "Ghee Thatte Idly",
        description: "Plate-sized thatte idli topped with a generous pour of aromatic desi ghee.",
        servingDetails: "1 pc",
        price: 130,
        tags: [],
        outlet: "sector-62",
        categoryId: "thatte-idly",
        categoryTitle: "Thatte Idly",
      },
      {
        id: "noida-ghee-podi-thatte-idly",
        name: "Ghee Podi Thatte Idly",
        description: "Plate idli dusted with spicy roasted gunpowder and drenched in golden ghee.",
        servingDetails: "1 pc",
        price: 150,
        tags: ["signature", "spicy"],
        outlet: "sector-62",
        categoryId: "thatte-idly",
        categoryTitle: "Thatte Idly",
      },
      {
        id: "noida-curry-leaf-podi-thatte-idly",
        name: "Curry Leaf Podi Thatte Idly",
        description: "Plate idli infused with aromatic roasted curry leaf spice blend and desi ghee.",
        servingDetails: "1 pc",
        price: 150,
        tags: ["chef-special"],
        outlet: "sector-62",
        categoryId: "thatte-idly",
        categoryTitle: "Thatte Idly",
      },
    ],
  },
  {
    id: "noida-dahi-vada",
    slug: "dahi-vada",
    title: "Dahi Vada",
    description: "Crispy vadas submerged in chilled seasoned yoghurt with mild spices.",
    image: "/images/sig-vada.jpg",
    items: [
      {
        id: "noida-dahi-vada-item",
        name: "Dahi Vada",
        description: "Crispy fried medu vada with seasoned mildly sweetened yogurt.",
        servingDetails: "1 pc",
        price: 120,
        tags: [],
        outlet: "sector-62",
        categoryId: "dahi-vada",
        categoryTitle: "Dahi Vada",
      },
    ],
  },
  {
    id: "noida-heritage-karnataka-dosa",
    slug: "heritage-karnataka-dosa",
    title: "Heritage Karnataka Dosa",
    description: "Crisp cast-iron griddled dosas prepared using authentic Karnataka fermented recipes.",
    image: "/images/DSC05117.jpg",
    items: [
      {
        id: "noida-benne-masala-dosa",
        name: "Benne Masala Dosa",
        description: "Crisp dosa stuffed with potato, onions and spices.",
        price: 159,
        tags: ["signature"],
        outlet: "sector-62",
        categoryId: "heritage-karnataka-dosa",
        categoryTitle: "Heritage Karnataka Dosa",
      },
      {
        id: "noida-benne-plain-dosa",
        name: "Benne Plain Dosa",
        description: "Crisp dosa topped with butter.",
        price: 140,
        tags: [],
        outlet: "sector-62",
        categoryId: "heritage-karnataka-dosa",
        categoryTitle: "Heritage Karnataka Dosa",
      },
      {
        id: "noida-bangalore-masala-dosa",
        name: "Bangalore Masala Dosa",
        description: "Crispy buttery masala dosa with Bangalore chutney.",
        price: 159,
        tags: ["signature"],
        outlet: "sector-62",
        categoryId: "heritage-karnataka-dosa",
        categoryTitle: "Heritage Karnataka Dosa",
      },
      {
        id: "noida-ghee-podi-masala-dosa",
        name: "Ghee Podi Masala Dosa",
        description: "Crispy dosa smeared with fiery spiced gunpowder and potato palya.",
        price: 159,
        tags: ["signature", "spicy"],
        outlet: "sector-62",
        categoryId: "heritage-karnataka-dosa",
        categoryTitle: "Heritage Karnataka Dosa",
      },
      {
        id: "noida-ghee-podi-plain-dosa",
        name: "Ghee Podi Plain Dosa",
        description: "Podi made with Bengal gram, urad dal and sesame seeds.",
        price: 140,
        tags: ["spicy"],
        outlet: "sector-62",
        categoryId: "heritage-karnataka-dosa",
        categoryTitle: "Heritage Karnataka Dosa",
      },
      {
        id: "noida-open-butter-masala-dosa",
        name: "Open Butter Masala Dosa 'Maharaja Special'",
        description: "Thick dosa with podi, potato palya, butter, coconut and carrot.",
        price: 159,
        tags: ["chef-special", "signature"],
        outlet: "sector-62",
        categoryId: "heritage-karnataka-dosa",
        categoryTitle: "Heritage Karnataka Dosa",
      },
      {
        id: "noida-set-masala-dosa",
        name: "Set Masala Dosa",
        description: "Pair of spongy set dosas served with spicy potato masala and sagu.",
        servingDetails: "2 pcs",
        price: 189,
        tags: [],
        outlet: "sector-62",
        categoryId: "heritage-karnataka-dosa",
        categoryTitle: "Heritage Karnataka Dosa",
      },
      {
        id: "noida-set-dosa",
        name: "Set Dosa",
        description: "Soft, spongy, melt-in-the-mouth griddled dosas served with sagu and chutney.",
        servingDetails: "2 pcs",
        price: 150,
        tags: [],
        outlet: "sector-62",
        categoryId: "heritage-karnataka-dosa",
        categoryTitle: "Heritage Karnataka Dosa",
      },
      {
        id: "noida-ragi-dosa",
        name: "Ragi Dosa",
        description: "Gluten-free dosa made from ragi (finger millet).",
        servingDetails: "2 pcs",
        price: 150,
        tags: ["chef-special"],
        outlet: "sector-62",
        categoryId: "heritage-karnataka-dosa",
        categoryTitle: "Heritage Karnataka Dosa",
      },
    ],
  },
  {
    id: "noida-thalis",
    slug: "thalis",
    title: "Thalis",
    description: "Wholesome South Indian thali meals served with curries, accompaniments, and sweets.",
    image: "/images/sig-thali.webp",
    items: [
      {
        id: "noida-mini-thali",
        name: "Mini Thali",
        description: "Rice + Sambar + Rasam + Vegetable Palya + Bajji + Papad + Pickle.",
        price: 200,
        tags: ["signature"],
        outlet: "sector-62",
        categoryId: "thalis",
        categoryTitle: "Thalis",
      },
      {
        id: "noida-mini-malabar-parotta-thali",
        name: "Mini Malabar Parotta Thali",
        description: "2 Malabar Parotta + Kurma + Rasam Rice + Papad + Bajji.",
        price: 200,
        tags: ["signature"],
        outlet: "sector-62",
        categoryId: "thalis",
        categoryTitle: "Thalis",
      },
    ],
  },
  {
    id: "noida-traditional-rice",
    slug: "traditional-rice",
    title: "South Indian Traditional Rice",
    description: "Aromatic seasoned rice prepared with homemade spice powders, tamarind, and tempering.",
    image: "/images/sig-thali.webp",
    items: [
      {
        id: "noida-vangi-bath",
        name: "Vangi Bath (Brinjal Rice)",
        description: "Rice and brinjals mixed with homemade spice powder.",
        price: 150,
        tags: ["signature"],
        outlet: "sector-62",
        categoryId: "traditional-rice",
        categoryTitle: "South Indian Traditional Rice",
      },
      {
        id: "noida-lemon-rice",
        name: "Lemon Rice",
        description: "Chitranna with turmeric and lemon juice.",
        price: 150,
        tags: ["jain"],
        outlet: "sector-62",
        categoryId: "traditional-rice",
        categoryTitle: "South Indian Traditional Rice",
      },
      {
        id: "noida-temple-puliyogare",
        name: "Temple Puliyogare (Tamarind Rice)",
        description: "Traditional tangy and spicy tamarind rice.",
        price: 150,
        tags: ["signature"],
        outlet: "sector-62",
        categoryId: "traditional-rice",
        categoryTitle: "South Indian Traditional Rice",
      },
      {
        id: "noida-rasam-rice",
        name: "Rasam Rice",
        description: "Steamed rice combined with hot rasam; served with papad.",
        price: 150,
        tags: ["spicy"],
        outlet: "sector-62",
        categoryId: "traditional-rice",
        categoryTitle: "South Indian Traditional Rice",
      },
    ],
  },
  {
    id: "noida-unique-must-try",
    slug: "unique-must-try",
    title: "Unique & Must Try",
    description: "Iconic regional snacks and tea-time delicacies from Karnataka.",
    image: "/images/sig-vada.jpg",
    items: [
      {
        id: "noida-mangalore-bun",
        name: "Mangalore Bun",
        description: "Mildly sweet banana-infused puffed fried bread served with spicy coconut chutney.",
        servingDetails: "1 pc",
        price: 100,
        tags: ["must-try", "signature"],
        outlet: "sector-62",
        categoryId: "unique-must-try",
        categoryTitle: "Unique & Must Try",
      },
      {
        id: "noida-maddur-vada",
        name: "Maddur Vada",
        description: "Crispy heritage fritters made with semolina, onions, and aromatic spices.",
        servingDetails: "3 pcs",
        price: 100,
        tags: ["must-try"],
        outlet: "sector-62",
        categoryId: "unique-must-try",
        categoryTitle: "Unique & Must Try",
      },
      {
        id: "noida-masala-vada",
        name: "Masala Vada",
        description: "Crunchy Bengal gram patties blended with shallots, fennel, and ginger.",
        servingDetails: "3 pcs",
        price: 120,
        tags: ["must-try"],
        outlet: "sector-62",
        categoryId: "unique-must-try",
        categoryTitle: "Unique & Must Try",
      },
    ],
  },
  {
    id: "noida-celebration-of-south-india",
    slug: "celebration-of-south-india",
    title: "Celebration of South India",
    description: "Authentic regional comfort foods from Karnataka and South India.",
    image: "/images/sig-thali.webp",
    items: [
      {
        id: "noida-kesari-bath",
        name: "Kesari Bath (Rava Kesari)",
        description: "Glistening saffron-infused semolina halwa cooked with pure ghee, cardamom, and toasted cashews.",
        price: 150,
        tags: [],
        outlet: "sector-62",
        categoryId: "celebration-of-south-india",
        categoryTitle: "Celebration of South India",
      },
      {
        id: "noida-vegetable-upma",
        name: "South Indian Vegetable Upma",
        description: "Semolina with mixed vegetables, curry leaves and spices.",
        price: 120,
        tags: ["jain"],
        outlet: "sector-62",
        categoryId: "celebration-of-south-india",
        categoryTitle: "Celebration of South India",
      },
      {
        id: "noida-chow-chow-bath",
        name: "Karnataka Special Chow-Chow Bath",
        description: "Rava Kesari and Upma served side-by-side in equal quantities.",
        price: 200,
        tags: ["signature"],
        outlet: "sector-62",
        categoryId: "celebration-of-south-india",
        categoryTitle: "Celebration of South India",
      },
      {
        id: "noida-khara-pongal",
        name: "Khara Pongal (Savoury)",
        description: "Comforting hot rice-and-lentil porridge with pepper, cumin, ginger, and ghee.",
        price: 130,
        tags: ["signature"],
        outlet: "sector-62",
        categoryId: "celebration-of-south-india",
        categoryTitle: "Celebration of South India",
      },
      {
        id: "noida-pongal-combo",
        name: "Pongal Combo (Sweet & Savoury)",
        description: "Combo of traditional sweet jaggery pongal and savoury khara pongal.",
        price: 200,
        tags: ["combo"],
        outlet: "sector-62",
        categoryId: "celebration-of-south-india",
        categoryTitle: "Celebration of South India",
      },
      {
        id: "noida-bisi-bele-bath",
        name: "Bisi Bele Bath (Rice-Lentil Dish)",
        description: "Karnataka hot lentil rice cooked with vegetables and homemade masala.",
        price: 130,
        tags: ["signature", "spicy"],
        outlet: "sector-62",
        categoryId: "celebration-of-south-india",
        categoryTitle: "Celebration of South India",
      },
      {
        id: "noida-akki-roti",
        name: "\"Akki\" Roti",
        description: "Rice flatbread.",
        servingDetails: "2 pcs",
        price: 150,
        tags: ["signature"],
        outlet: "sector-62",
        categoryId: "celebration-of-south-india",
        categoryTitle: "Celebration of South India",
      },
      {
        id: "noida-ragi-roti",
        name: "\"Ragi\" Roti aka Finger Millet",
        description: "Handmade savoury gluten-free flatbread.",
        servingDetails: "2 pcs",
        price: 150,
        tags: ["chef-special"],
        outlet: "sector-62",
        categoryId: "celebration-of-south-india",
        categoryTitle: "Celebration of South India",
      },
      {
        id: "noida-poori",
        name: "Poori",
        description: "Served with vegetable kurma and chutney.",
        servingDetails: "2 pcs",
        price: 150,
        tags: [],
        outlet: "sector-62",
        categoryId: "celebration-of-south-india",
        categoryTitle: "Celebration of South India",
      },
      {
        id: "noida-malabar-parotta",
        name: "Malabar Parotta",
        description: "Soft, flaky, layered flatbread.",
        servingDetails: "2 pcs",
        price: 150,
        tags: [],
        outlet: "sector-62",
        categoryId: "celebration-of-south-india",
        categoryTitle: "Celebration of South India",
      },
    ],
  },
  {
    id: "noida-speciality-hot-beverages",
    slug: "speciality-hot-beverages",
    title: "Speciality Hot Beverages",
    description: "Traditional filter coffee, spiced teas, and warm soothing beverages.",
    image: "/images/coffee-pour.webp",
    items: [
      {
        id: "noida-special-filter-coffee",
        name: "Special Filter Coffee",
        description: "Traditional filter coffee with hot milk.",
        price: 69,
        tags: ["signature"],
        outlet: "sector-62",
        categoryId: "speciality-hot-beverages",
        categoryTitle: "Speciality Hot Beverages",
      },
      {
        id: "noida-coffee-and-jaggery",
        name: "Coffee and \"Jaggery\"",
        description: "Karnataka-style filter coffee sweetened with jaggery/gur.",
        price: 79,
        tags: [],
        outlet: "sector-62",
        categoryId: "speciality-hot-beverages",
        categoryTitle: "Speciality Hot Beverages",
      },
      {
        id: "noida-black-coffee",
        name: "Black Coffee",
        description: "Dark roasted Arabica and Peaberry coffee.",
        price: 50,
        tags: [],
        outlet: "sector-62",
        categoryId: "speciality-hot-beverages",
        categoryTitle: "Speciality Hot Beverages",
      },
      {
        id: "noida-special-tea",
        name: "Special Tea",
        description: "Karnataka shade-grown tea.",
        price: 69,
        tags: [],
        outlet: "sector-62",
        categoryId: "speciality-hot-beverages",
        categoryTitle: "Speciality Hot Beverages",
      },
      {
        id: "noida-ginger-tea",
        name: "Ginger Tea",
        description: "Tea flavored with freshly grated ginger.",
        price: 69,
        tags: [],
        outlet: "sector-62",
        categoryId: "speciality-hot-beverages",
        categoryTitle: "Speciality Hot Beverages",
      },
      {
        id: "noida-masala-tea",
        name: "Masala Tea",
        description: "Tea with aromatic spices.",
        price: 69,
        tags: [],
        outlet: "sector-62",
        categoryId: "speciality-hot-beverages",
        categoryTitle: "Speciality Hot Beverages",
      },
      {
        id: "noida-lemon-tea",
        name: "Lemon Tea",
        description: "Tea with lemon juice.",
        price: 69,
        tags: [],
        outlet: "sector-62",
        categoryId: "speciality-hot-beverages",
        categoryTitle: "Speciality Hot Beverages",
      },
      {
        id: "noida-black-tea",
        name: "Black Tea",
        description: "Tea infusion from the copper boiler.",
        price: 50,
        tags: [],
        outlet: "sector-62",
        categoryId: "speciality-hot-beverages",
        categoryTitle: "Speciality Hot Beverages",
      },
      {
        id: "noida-hot-rasam",
        name: "Hot Rasam",
        description: "Mild spiced South Indian soup-like dish.",
        price: 100,
        tags: ["spicy"],
        outlet: "sector-62",
        categoryId: "speciality-hot-beverages",
        categoryTitle: "Speciality Hot Beverages",
      },
      {
        id: "noida-hot-horlicks",
        name: "Hot Horlicks",
        description: "Warm soothing malt drink.",
        price: 100,
        tags: [],
        outlet: "sector-62",
        categoryId: "speciality-hot-beverages",
        categoryTitle: "Speciality Hot Beverages",
      },
      {
        id: "noida-hot-bournvita",
        name: "Hot Bournvita",
        description: "Warm chocolate malt drink.",
        price: 100,
        tags: [],
        outlet: "sector-62",
        categoryId: "speciality-hot-beverages",
        categoryTitle: "Speciality Hot Beverages",
      },
    ],
  },
  {
    id: "noida-to-keep-you-cool",
    slug: "to-keep-you-cool",
    title: "To Keep You Cool",
    description: "Chilled coolers, iced filter coffees, and refreshing spiced buttermilk.",
    image: "/images/coffee-pour.webp",
    items: [
      {
        id: "noida-iced-filter-coffee",
        name: "Iced Filter Coffee",
        description: "Strong, sweet and topped with bubbly froth.",
        price: 120,
        tags: ["signature"],
        outlet: "sector-62",
        categoryId: "to-keep-you-cool",
        categoryTitle: "To Keep You Cool",
      },
      {
        id: "noida-iced-black-coffee",
        name: "Iced Black Coffee",
        description: "Iced dark roasted Arabica and Peaberry coffee.",
        price: 100,
        tags: [],
        outlet: "sector-62",
        categoryId: "to-keep-you-cool",
        categoryTitle: "To Keep You Cool",
      },
      {
        id: "noida-lemon-ice-tea",
        name: "Lemon Ice Tea",
        description: "Karnataka tea with lemon, sugar and ice.",
        price: 120,
        tags: [],
        outlet: "sector-62",
        categoryId: "to-keep-you-cool",
        categoryTitle: "To Keep You Cool",
      },
      {
        id: "noida-neer-majjige",
        name: "Neer Majjige",
        description: "Buttermilk with curd, water, salt, cumin, ginger and coriander.",
        price: 120,
        tags: ["jain", "signature"],
        outlet: "sector-62",
        categoryId: "to-keep-you-cool",
        categoryTitle: "To Keep You Cool",
      },
    ],
  },
];

export const defaultMenuCategories: MenuCategory[] = janpathMenuCategories;
export const menuCategories: MenuCategory[] = janpathMenuCategories;

/**
 * Gokulam Janpath Specific Menu Data
 */
export const janpathMenu: OutletMenuInfo = {
  id: "delhi-janpath",
  slug: "janpath",
  name: "Gokulam Janpath",
  tagline: "Connaught Place, New Delhi",
  location: "Janpath, Connaught Place, New Delhi",
  address: "G-7, Janpath Market, Connaught Place, New Delhi 110001",
  hours: "11:00 AM – 11:00 PM, all days",
  phone: "+91 11 4155 2233",
  categories: janpathMenuCategories,
};

/**
 * Gokulam Sector 62 (Noida) Specific Menu Data
 */
export const sector62Menu: OutletMenuInfo = {
  id: "noida-sector-62",
  slug: "sector-62",
  name: "Gokulam Sector 62",
  tagline: "Noida Electronic City",
  location: "Sector 62, Noida Electronic City",
  address: "Sector 62, Noida Electronic City, Uttar Pradesh",
  hours: "8:00 AM – 8:00 PM, all days",
  phone: "+91 11 4155 2233",
  categories: noidaMenuCategories,
};

export const outletMenus: Record<string, OutletMenuInfo> = {
  "janpath": janpathMenu,
  "delhi-janpath": janpathMenu,
  "janpadh": janpathMenu,
  "gokulam-janpath": janpathMenu,
  "gokulam-janpadh": janpathMenu,
  "sector-62": sector62Menu,
  "noida-sector-62": sector62Menu,
  "sector62": sector62Menu,
  "noida": sector62Menu,
  "gokulam-noida": sector62Menu,
  "gokulam-sector-62": sector62Menu,
};

export function getOutletMenu(slugOrOutlet: string): OutletMenuInfo | undefined {
  const normalized = slugOrOutlet.toLowerCase().trim();
  return outletMenus[normalized];
}

export const allOutletMenus: OutletMenuInfo[] = [janpathMenu, sector62Menu];

